### ISSUE TITLE
Nuxt.js and APM Vendors

### ISSUE THREAD

**Issue by astorm** [nuxt/nuxt-cli#4]
👋 -- I'm unsure if this is the right place/repo for this.  I'm happy to move this conversation elsewhere if there's a more appropriate location.

Some of our users are running into issues when trying to use NuxtJS with [the Elastic Node.js APM Agent](https://github.com/elastic/apm-agent-nodejs/issues/1933).  After investigating the issue, we realized that the `nuxt` command line bootstraps an application in such a way that it's (seemingly) impossible for _any_ server side Node.js APM Agent (Elastic, New Relic, OpenTelemetry, etc.) to hook into the `http` and `https` modules in order to instrument incoming web transactions. 

The main issue is APM Agents (for most APM vendors) need to run _before_ an instrumented module is first `require`d in by NodeJS -- and the first time a user's able to run their own code with the `nuxt` CLI seems to be in `nuxt.config.js`.  By this time the modules we want to hook have already been loaded.  

Question: Do you'all have known science/a recommended way of handling the APM scenario?

Feature Request: If not, ideally we'd like to have the ability to specify a "pre-bootstrap" file for the `nuxt` CLI that would let users run some code before running the CLI `start` and `dev` commands.  

If you're not open to adding this feature, would you be open to a PR that implemented it?

If you're not open to that PR, would you have any suggestions for what sort of PR you _would_ be open to in order to fix this issue?

**Comment by pi0** [comment]
Hi @astorm. Thanks for detailed information about requirement.

As a quick solution, we may use `node -r` flag:


```json
{
  "scripts": {
    "start": "node -r elastic-apm-node node_modules/nuxt/.bin/nuxt"
  }
}
```

We can also [use nuxt programmatically](https://nuxtjs.org/docs/2.x/internals-glossary/nuxt/) as a middleware and following similar guide used for Express: (not recommended unless _have to_

```js
const { loadNuxt } = require('nuxt')
const nuxtPromise = loadNuxt('start')
app.use((req, res) => { nuxtPromise.then(nuxt => nuxt.render(req, res)) })
```


----

Nuxt 2 repository is in maintenance now but we have two possibilities in the future for more integrated solution for elastic apm agent:

- Nuxt Sigma project which is a ground up rewrite of SSR bundler that creates standalone entrypoint in `.out/server` and we can add preloads and it is also independent from CLI/Environment/Runtime. ([demo you can locally try on nuxt2](https://github.com/nuxt/sigma-demo))
- `nuxt-cli` which is being developed for nuxt@3, which _may_ support `-r` flag (like node) but i would still recommend using server bundler since such extensions may be added by a nuxt module but with cli, we always need manual setup.

**Comment by astorm** [comment]
@pi0 That's perfect, thank you.  We'll pass on this information to our customers/users and we'll keep an eye out for Nuxt 3.  Keep up the great work!

**Comment by sowinski** [comment]
Hi,

can someone explain in detail how to integrate elastic-apm-node in a Server Side Rendered nuxt application?

So from what I have read here is:

1). >> Open package.json

Replace 
```
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
....
```
with 
```
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "node -r elastic-apm-node node_modules/nuxt/.bin/nuxt"
...

```

But how/where do I set the configuration?

Just using ENVIRONMENT_VARIABLES likes described here:
https://www.elastic.co/guide/en/apm/agent/nodejs/current/custom-stack.html#custom-stack-advanced-configuration
Or do I need any further steps?


**EDIT1**
node_modules/nuxt/.bin/nuxt
This path does not exist in 2022. Can someone help? :=

**EDIT2**
Just remove the dot in node_modules/nuxt/.bin/nuxt and it will work again.
But there is still my question => How do I do the configuration?

**Comment by astorm** [comment]
> Just using ENVIRONMENT_VARIABLES likes described here
> ...
>  But there is still my question => How do I do the configuration?

That's right -- you'll want/need to use the environment variables to configure your agent.  

Also, FWIW, you may need to modify your `-r` invocation to include the path to `start.js`

```
node -r elastic-apm-node/start.js node_modules/nuxt/.bin/nuxt
```

**Comment by sowinski** [comment]
@astorm 
Thank you for the fast response.

I did it like here described and it works
https://stackoverflow.com/questions/65484826/what-is-the-best-way-to-add-apm-to-nuxtjs-project/71161518#71161518

> Also, FWIW, you may need to modify your -r invocation to include the path to start.js
> 
> `node -r elastic-apm-node/start.js node_modules/nuxt/.bin/nuxt`
With that, I do not need the start it on my own, correct?

The following is not necessary any more, right?
```
const nodeApm = require('elastic-apm-node')

if (!nodeApm.isStarted()) { 
    nodeApm.start()
}
```

But I have one problem yet. Errors are not logged. Do you have an idea why? (I see all calls, also I see in the statistics failing requests but no errors/exceptions are logged.)
